services:
  backend:
    build: ./backend
    container_name: myapp_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: myapp_frontend
    restart: always
    ports:
      - "8080:80"